version: 1.0.{build}
os:
  - Visual Studio 2015
clone_depth: 1
configuration:
  - Debug
  - Release
platform:
  - Win32
  - x64
environment:
  OPENSSL_DIR: C:\OpenSSL
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly-2018-10-24
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly

build_script: appveyor.bat
